version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  nodejs:
    image: node:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - db

networks:
  mynetwork:
    driver: bridge
