#pragma once
#define PIN_SENSOR_LIGHT PIN_A4
#define PIN_SENSOR_SOUND PIN_A3
#define PIN_SENSOR_FLAME PIN_A1
#define PIN_SENSOR_MOVEMEMT 7
#define PIN_SENSOR_DHT PIN_A0
#define PIN_BUTTON 6
#define PIN_LED_BLUE 8
#define PIN_LED_GREEN 9
#define DHTTYPE DHT11